---
- name: Pre_Jenkins
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt update && sudo apt-get -y install python'
     ignore_errors: True


- name: Jenkins
  hosts: all
  become: yes
  become_method: sudo
  
  roles:
  - { role: common , tags: "common"} 
  - { role: cloud , tags: "cloud"} 
  - { role: nginx , tags: "nginx"}
  - { role: jenkins , tags: "jenkins"} 
  - { role: end , tags: "end"}
