---
- name: Jenkins
  hosts: jenkins
  become: yes
  become_method: sudo
  become_user: ubuntu
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'


- name: Jenkins
  hosts: jenkins
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
  - { role: common , tags: "common"} 
  - { role: jenkins  , tags: "jenkins"} 
  - { role: nginx , tags: "nginx"}
  - { role: end, tags: "end" }

    