---
# Stable url https://pkg.jenkins.io/debian-stable
# Latest url https://pkg.jenkins.io/debian

- debug:
    msg: Jenkins will be installed on {{ ansible_distribution }} 

- name: Add an Apt signing jenkins key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add jenkins repository 
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins
    update_cache: yes
    
- name: Install jenkins
  apt:
    name: jenkins
    
- name: Get Jenkins version
  shell: sudo sh -c 'echo "Jenkins $(apt show jenkins | grep Version)" 1>> /data/logs/install_version.txt'
