- include: "{{ansible_os_family}}.yml"

- name: Create User for jenkins
  user: 
    name: jenkins
    comment: jenkins 
    password_lock: yes
       
- name: rm -rf /data/wwwroot/jenkins
  shell: rm -rf /data/wwwroot/jenkins

- name: Create a Jenkins directory if it does not exist
  file:
    path: /data/wwwroot/jenkins
    state: directory
    recurse: yes
  remote_user: jenkins

- name: change file permissions
  shell: |
    setfacl -R -m u:jenkins:rwx /data/wwwroot 
    setfacl -R -m u:jenkins:rwx /data/logs

- name: download jenkins
  shell: wget -P /data/wwwroot http://mirrors.jenkins.io/war-stable/latest/jenkins.war
  remote_user: jenkins

- name: Setting jenkins service
  copy:
    src: jenkins.service
    dest: /lib/systemd/system/jenkins.service

- name: enable and restart jenkins
  service: name=jenkins state=restarted enabled=yes

- name: input jenkins version
  shell: |
    sleep 60
    sudo echo jenkins version $(cat /data/wwwroot/jenkins/config.xml |grep version |sed -n 2p |tr -d "</>version") |sudo tee -a /data/logs/install_version.txt
  
- name: Check Jenkins Service
  shell: systemctl status jenkins | grep Active*
  register: check_jenkins_service
  notify: check_jenkins_service
