# Install Jenkins by OS_family
- debug:
    msg: Jenkins will be installed on {{ ansible_distribution }} 

- include: "{{ansible_os_family}}.yml"

# Enable service
- name: restart jenkins
  service: name=jenkins state=restarted enabled=yes

- name: Create Jenkins directory
  shell: mkdir /data/wwwroot/jenkins
  
- name: Download jenkins CLI
  shell: wget -O /data/wwwroot/jenkins/jenkins-cli.jar http://localhost/jnlpJars/jenkins-cli.jar
    
# set soft link, -b over
# ln -sb src des
- name: set soft link
  shell: |
    ln -sb /usr/share/jenkins  /data/wwwroot/jenkins/jenkins
    ln -sb /var/log/jenkins/ /data/logs/jenkins

# display version and service state of components
- name: Get Jenkins version
  shell: sudo sh -c 'echo "Jenkins version can not got now" 1>> /data/logs/install_version.txt'

- name: Check Jenkins Service
  shell: systemctl status jenkins | grep Active*
  register: check_jenkins_service
  notify: check_jenkins_service
