# Pre-installation
- name: Create a Jenkins directory if it does not exist
  file:
    path: /data/wwwroot/jenkins
    state: directory
    
# Install Jenkins by OS_family
- include: "{{ansible_os_family}}.yml"

# Enable service
- name: enable and restart jenkins
  service: name=jenkins state=restarted enabled=yes

- name: Copy init_password.service
  template:
    src: init_password.service
    dest: /lib/systemd/system/init-password.service
    
- name: enable init-password service
  service: name=init-password enabled=yes
    
# set soft link, -b over
# ln -sb src des
- name: set soft link
  shell: |
    ls -sb /usr/lib/jenkins /data/wwwroot/jenkins/jenkins.war
    ln -sb /var/lib/jenkins /data/wwwroot/jenkins/jenkins
    ln -sb /var/log/jenkins/ /data/logs/jenkins

# display version and service state of components
- name: Check Jenkins Service
  shell: systemctl status jenkins | grep Active*
  register: check_jenkins_service
  notify: check_jenkins_service
