# Install Jenkins by OS_family
- debug:
    msg: Jenkins will be installed on {{ ansible_distribution }} 

- include: "{{ansible_os_family}}.yml"

# Enable service
- name: restart jenkins
  service: name=jenkins state=restarted enabled=yes