- name: Add Jenkins repositories
  shell: |
    wget -O /etc/yum.repos.d/jenkins.repo \
        https://pkg.jenkins.io/redhat-stable/jenkins.repo
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    yum upgrade
    yum install jenkins java-1.8.0-openjdk-devel

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest
