- debug:
    msg: Jenkins will be installed on {{ ansible_distribution }} 
    
- name: Add Jenkins repositories
  shell: |
    wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    yum upgrade -y
  failed_when: False

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest
    
- name: Get Jenkins version
  shell: sudo sh -c 'echo "Jenkins $(yum info jenkins | grep Version)" 1>> /data/logs/install_version.txt'
