- name: Add Jenkins repositories
  yum_repository:
    name: jenkins
    file: jenkins
    description: Jenkins RPM Repository
    baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    enabled: yes

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest